name: qhali_tarpuy_app
description: Qhali Tarpuy aplicación Android para el monitoreo calidad de los cultivos mediante la irrigación y fertilización inteligente.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  bloc: ^8.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^5.1.10
  intl: ^0.17.0
  mqtt_client: ^9.7.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.3.57
  syncfusion_flutter_core: ^20.4.42
  syncfusion_flutter_gauges: ^20.3.57

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
